server:
  port: 30082
spring:
  application:
    name: "product-service"
  batch:
    jdbc:
      initialize-schema: "always"
  cache:
    type: "redis"
  cloud:
    zookeeper:
      connect-string: "zookeeper"
  data:
    mongodb:
      host: "mongo"
      database: "pos"
  datasource:
    url: "jdbc:mysql://mysql/pos"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "root"
  redis:
    host: "redis"
    database: 0
