server:
  port: 30083
spring:
  application:
    name: "order-service"
  cloud:
    stream:
      bindings:
        createOrder-out-0:
          destination: "newOrders"
      kafka:
        binder:
          brokers: "kafka"
          auto-create-topics: true
    zookeeper:
      connect-string: "zookeeper"
  data:
    mongodb:
      host: "mongo"
      database: "pos"
