version: "3"

services:
  zookeeper:
    image: "bitnami/zookeeper:3.8"
    environment:
      - "ZOO_SERVER_ID=1"
      - "ALLOW_ANONYMOUS_LOGIN=yes"
    ports:
      - "30001:2181"

  kafka:
    image: "bitnami/kafka:3.1"
    environment:
      - "ALLOW_PLAINTEXT_LISTENER=yes"
      - "KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true"
      - "KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181"
      - "KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT"
      - "KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:30002"
      - "KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://kafka:30002"
      - "KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT"
    ports:
      - "30002:30002"

  mysql:
    image: "bitnami/mysql:8.0"
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
    volumes:
      - "./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql"
    ports:
      - "30003:3306"

  mongo:
    image: "bitnami/mongodb:5.0"
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
    ports:
      - "30004:27017"

  redis:
    image: "bitnami/redis:6.2"
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"

  pos_gateway:
    build:
      context: "."
      dockerfile: "pos-gateway.Dockerfile"
    ports:
      - "30080:30080"
    depends_on:
      - pos_services_cart
      - pos_services_product
      - pos_services_delivery
      - pos_services_order

  pos_services_cart:
    build:
      context: "."
      dockerfile: "pos-services-cart.Dockerfile"
    ports:
      - "30081:30081"
    depends_on:
      - mongo
      - zookeeper

  pos_services_product:
    build:
      context: "."
      dockerfile: "pos-services-product.Dockerfile"
    ports:
      - "30082:30082"
    volumes:
      - "./pos-services-product/src/main/resources/data:/data:ro"
    depends_on:
      - mongo
      - mysql
      - redis
      - zookeeper

  pos_services_order:
    build:
      context: "."
      dockerfile: "pos-services-order.Dockerfile"
    ports:
      - "30083:30083"
    depends_on:
      - kafka
      - mongo
      - zookeeper

  pos_services_delivery:
    build:
      context: "."
      dockerfile: "pos-services-delivery.Dockerfile"
    ports:
      - "30084:30084"
    depends_on:
      - kafka
      - mongo
      - zookeeper

