server:
  port: 30084
spring:
  application:
    name: "delivery-service"
  cloud:
    stream:
      bindings:
        createDelivery-in-0:
          destination: "newOrders"
      kafka:
        binder:
          brokers:
            - "PLAINTEXT://kafka:30002"
          auto-create-topics: true
    zookeeper:
      connect-string: "zookeeper"
  data:
    mongodb:
      host: "mongo"
      database: "pos"
