server:
  port: 30080
spring:
  application:
    name: "gateway"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: "cart-service"
          uri: "lb://cart-service"
          predicates:
            - "Path=/api/carts/**"
        - id: "delivery-service"
          uri: "lb://delivery-service"
          predicates:
            - "Path=/api/deliveries/**"
        - id: "order-service"
          uri: "lb://order-service"
          predicates:
            - "Path=/api/orders/**"
        - id: "product-service"
          uri: "lb://product-service"
          predicates:
            - "Path=/api/products/**"
      default-filters:
        - "DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin"
      globalcors:
        corsConfigurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins:
              - "http://localhost:3000"
              - "https://hoppscotch.io"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
    zookeeper:
      connect-string: "localhost:30001"